### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by mb720** [wbolster/whip#1]
When calling `whip-cli` on Arch Linux, I get this error message:

    Traceback (most recent call last):
      File "/usr/bin/whip-cli", line 33, in <module>
        sys.exit(load_entry_point('whip==0.1', 'console_scripts', 'whip-cli')())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/bin/whip-cli", line 25, in importlib_load_entry_point
        return next(matches).load()
              ^^^^^^^^^^^^^
    StopIteration

Using Python 3.11.5.

**Comment by wbolster** [comment]
i think this is an installation issue. can you try in a `venv` or inside a docker container and provide more details?
